// services/nbaLogos.js
export const teamLogos = {
  "Celtics": `${process.env.PUBLIC_URL}/images/nba-logos/boston-celtics.svg`,
  "Nets": `${process.env.PUBLIC_URL}/images/nba-logos/brooklyn-nets.svg`,
  "Knicks": `${process.env.PUBLIC_URL}/images/nba-logos/new-york-knicks.svg`,
  "76ers": `${process.env.PUBLIC_URL}/images/nba-logos/philadelphia-76ers.svg`,
  "Raptors": `${process.env.PUBLIC_URL}/images/nba-logos/toronto-raptors.svg`,
  "Bucks": `${process.env.PUBLIC_URL}/images/nba-logos/milwaukee-bucks.svg`,
  "Bulls": `${process.env.PUBLIC_URL}/images/nba-logos/chicago-bulls.svg`,
  "Cavaliers": `${process.env.PUBLIC_URL}/images/nba-logos/cleveland-cavaliers.svg`,
  "Pistons": `${process.env.PUBLIC_URL}/images/nba-logos/detroit-pistons.svg`,
  "Pacers": `${process.env.PUBLIC_URL}/images/nba-logos/indiana-pacers.svg`,
  "Hawks": `${process.env.PUBLIC_URL}/images/nba-logos/atlanta-hawks.svg`,
  "Lakers": `${process.env.PUBLIC_URL}/images/nba-logos/los-angeles-lakers.svg`,
  "Warriors": `${process.env.PUBLIC_URL}/images/nba-logos/golden-state-warriors.svg`,
  "Heat": `${process.env.PUBLIC_URL}/images/nba-logos/miami-heat.svg`,
  "Nuggets": `${process.env.PUBLIC_URL}/images/nba-logos/denver-nuggets.svg`,
  "Thunder": `${process.env.PUBLIC_URL}/images/nba-logos/oklahoma-city-thunder.svg`,
  "Clippers": `${process.env.PUBLIC_URL}/images/nba-logos/los-angeles-clippers.svg`,
  "Suns": `${process.env.PUBLIC_URL}/images/nba-logos/phoenix-suns.svg`,
  "Mavericks": `${process.env.PUBLIC_URL}/images/nba-logos/dallas-mavericks.svg`,
  "Grizzlies": `${process.env.PUBLIC_URL}/images/nba-logos/memphis-grizzlies.svg`,
  "Kings": `${process.env.PUBLIC_URL}/images/nba-logos/sacramento-kings.svg`,
  "Jazz": `${process.env.PUBLIC_URL}/images/nba-logos/utah-jazz.svg`,
  "Timberwolves": `${process.env.PUBLIC_URL}/images/nba-logos/minnesota-timberwolves.svg`,
  "Pelicans": `${process.env.PUBLIC_URL}/images/nba-logos/new-orleans-pelicans.svg`,
  "Trail Blazers": `${process.env.PUBLIC_URL}/images/nba-logos/portland-trail-blazers.svg`,
  "Rockets": `${process.env.PUBLIC_URL}/images/nba-logos/houston-rockets.svg`,
  "Spurs": `${process.env.PUBLIC_URL}/images/nba-logos/san-antonio-spurs.svg`,
  "Hornets": `${process.env.PUBLIC_URL}/images/nba-logos/charlotte-hornets.svg`,
  "Magic": `${process.env.PUBLIC_URL}/images/nba-logos/orlando-magic.svg`,
  "Wizards": `${process.env.PUBLIC_URL}/images/nba-logos/washington-wizards.svg`,
};