// services/nbaLogos.js
const BASE_URL = process.env.PUBLIC_URL || '/';

export const teamLogos = {
  "Celtics": `${BASE_URL}images/nba-logos/boston-celtics.svg`,
  "Nets": `${BASE_URL}images/nba-logos/brooklyn-nets.svg`,
  "Knicks": `${BASE_URL}images/nba-logos/new-york-knicks.svg`,
  "76ers": `${BASE_URL}images/nba-logos/philadelphia-76ers.svg`,
  "Raptors": `${BASE_URL}images/nba-logos/toronto-raptors.svg`,
  "Bucks": `${BASE_URL}images/nba-logos/milwaukee-bucks.svg`,
  "Bulls": `${BASE_URL}images/nba-logos/chicago-bulls.svg`,
  "Cavaliers": `${BASE_URL}images/nba-logos/cleveland-cavaliers.svg`,
  "Pistons": `${BASE_URL}images/nba-logos/detroit-pistons.svg`,
  "Pacers": `${BASE_URL}images/nba-logos/indiana-pacers.svg`,
  "Hawks": `${BASE_URL}images/nba-logos/atlanta-hawks.svg`,
  "Lakers": `${BASE_URL}images/nba-logos/los-angeles-lakers.svg`,
  "Warriors": `${BASE_URL}images/nba-logos/golden-state-warriors.svg`,
  "Heat": `${BASE_URL}images/nba-logos/miami-heat.svg`,
  "Nuggets": `${BASE_URL}images/nba-logos/denver-nuggets.svg`,
  "Thunder": `${BASE_URL}images/nba-logos/oklahoma-city-thunder.svg`,
  "Clippers": `${BASE_URL}images/nba-logos/los-angeles-clippers.svg`,
  "Suns": `${BASE_URL}images/nba-logos/phoenix-suns.svg`,
  "Mavericks": `${BASE_URL}images/nba-logos/dallas-mavericks.svg`,
  "Grizzlies": `${BASE_URL}images/nba-logos/memphis-grizzlies.svg`,
  "Kings": `${BASE_URL}images/nba-logos/sacramento-kings.svg`,
  "Jazz": `${BASE_URL}images/nba-logos/utah-jazz.svg`,
  "Timberwolves": `${BASE_URL}images/nba-logos/minnesota-timberwolves.svg`,
  "Pelicans": `${BASE_URL}images/nba-logos/new-orleans-pelicans.svg`,
  "Trail Blazers": `${BASE_URL}images/nba-logos/portland-trail-blazers.svg`,
  "Rockets": `${BASE_URL}images/nba-logos/houston-rockets.svg`,
  "Spurs": `${BASE_URL}images/nba-logos/san-antonio-spurs.svg`,
  "Hornets": `${BASE_URL}images/nba-logos/charlotte-hornets.svg`,
  "Magic": `${BASE_URL}images/nba-logos/orlando-magic.svg`,
  "Wizards": `${BASE_URL}images/nba-logos/washington-wizards.svg`,
};