// services/nbaLogos.js
export const teamLogos = {
  "Celtics": `${process.env.PUBLIC_URL}/images/nba-logos/celtics.svg`,
  "Nets": `${process.env.PUBLIC_URL}/images/nba-logos/nets.svg`,
  "Knicks": `${process.env.PUBLIC_URL}/images/nba-logos/knicks.svg`,
  "76ers": `${process.env.PUBLIC_URL}/images/nba-logos/76ers.svg`,
  "Raptors": `${process.env.PUBLIC_URL}/images/nba-logos/raptors.svg`,
  "Bucks": `${process.env.PUBLIC_URL}/images/nba-logos/bucks.svg`,
  "Bulls": `${process.env.PUBLIC_URL}/images/nba-logos/bulls.svg`,
  "Cavaliers": `${process.env.PUBLIC_URL}/images/nba-logos/cavaliers.svg`,
  "Pistons": `${process.env.PUBLIC_URL}/images/nba-logos/pistons.svg`,
  "Pacers": `${process.env.PUBLIC_URL}/images/nba-logos/pacers.svg`,
  "Lakers": `${process.env.PUBLIC_URL}/images/nba-logos/lakers.svg`,
  "Warriors": `${process.env.PUBLIC_URL}/images/nba-logos/warriors.svg`,
  "Heat": `${process.env.PUBLIC_URL}/images/nba-logos/heat.svg`,
  "Nuggets": `${process.env.PUBLIC_URL}/images/nba-logos/nuggets.svg`,
  "Thunder": `${process.env.PUBLIC_URL}/images/nba-logos/thunder.svg`,
  "Clippers": `${process.env.PUBLIC_URL}/images/nba-logos/clippers.svg`,
  "Suns": `${process.env.PUBLIC_URL}/images/nba-logos/suns.svg`,
  "Mavericks": `${process.env.PUBLIC_URL}/images/nba-logos/mavericks.svg`,
  "Grizzlies": `${process.env.PUBLIC_URL}/images/nba-logos/grizzlies.svg`,
  "Kings": `${process.env.PUBLIC_URL}/images/nba-logos/kings.svg`,
  "Jazz": `${process.env.PUBLIC_URL}/images/nba-logos/jazz.svg`,
  "Timberwolves": `${process.env.PUBLIC_URL}/images/nba-logos/timberwolves.svg`,
  "Pelicans": `${process.env.PUBLIC_URL}/images/nba-logos/pelicans.svg`,
  "Trail Blazers": `${process.env.PUBLIC_URL}/images/nba-logos/trail-blazers.svg`,
  "Rockets": `${process.env.PUBLIC_URL}/images/nba-logos/rockets.svg`,
  "Spurs": `${process.env.PUBLIC_URL}/images/nba-logos/spurs.svg`,
  "Hornets": `${process.env.PUBLIC_URL}/images/nba-logos/hornets.svg`,
  "Magic": `${process.env.PUBLIC_URL}/images/nba-logos/magic.svg`,
  "Wizards": `${process.env.PUBLIC_URL}/images/nba-logos/wizards.svg`,
};